### ISSUE TITLE
Files with mismatching audio/video durations don't have correct file duration

### ISSUE THREAD

**Issue by sashazxtt** [davedoesdev/webm-muxer.js#19]
Hello!
This appears to be an issue in the EBML. I'm not sure how to solve it, exaclty.
Here is the issue: the recorded file duration is not correct if a video stream stops before an audio stream.
Here are the steps:
1. Create a file with both audio and video tracks
2. Start recording
3. Remove the video track (however method you have available - stop()/cancel(), etc).
4. Continue recording with audio only for lets say 30 seconds
5. Stop recording.
6. Play the file back. Observe that the last 30 seconds are not reflected in the total file duration

Looking at the EBML code, when type of the file is 'both', the last video timestamp available is used to compute the file duration. And that will not account for the audio only portion.
Not sure what the best way to solve this issue is...

Thanks!

**Comment by sashazxtt** [comment]
I have worked around this issue by inserting a dummy video frame upon stopping a recording.

**Comment by davedoesdev** [comment]
@sashazxtt I can't repro this :(

If I make this change to `demo.js`:

```diff
diff --git a/demo.js b/demo.js
index d60362e..22fb826 100644
--- a/demo.js
+++ b/demo.js
@@ -94,6 +94,8 @@ start_el.addEventListener('click', async function () {
     const video_readable = (new MediaStreamTrackProcessor(video_track)).readable;
     const video_settings = video_track.getSettings();
 
+    setTimeout(() => video_track.stop(), 5000);
+
     const encoder_constraints = {
         //codec: 'avc1.42E01E',
         codec: vp9_codec,
```

and let the audio record for 30s, then the resulting file shows duration 30s, not 5s, using mkvinfo and ffplay.

Which app are you using to see the duration?

**Comment by davedoesdev** [comment]
Note in order to get correct ordering, I've made encoding of audio/video wait until the other catches up: https://github.com/davedoesdev/webm-muxer.js/blob/main/webm-worker.js#L122

I ended up with this approach as it was the only one I found which reliably ordered the frames correctly and predictably.

Therefore, if the video stops early, the audio is buffered up until the stream ends. So if the file isn't finalised due to stream ending, you'll not see the audio after the video.

The `audio_queue_limit` options can be set to force the remaining audio to be output after so many samples have been received without a video frame.

However, I think repeating the final (or a blank) video frame at regular intervals after the video "stops" is the correct solution in order to keep recording the audio samples. I took this approach in [streamana](https://github.com/davedoesdev/streamana) when the camera is off.

**Comment by davedoesdev** [comment]
@sashazxtt closing as this seems to be a consequence of how I'm doing the frame/sample ordering.
Feel free to reopen if you disagree!

**Comment by davedoesdev** [comment]
As an extra note, I can see the code going into the `"both"` section here:

https://github.com/davedoesdev/webm-muxer.js/blob/main/EBML.js#L642

and so it uses whatever it has received last.

@sashazxtt you said:

> Looking at the EBML code, when type of the file is 'both', the last video timestamp available is used to compute the file duration.

Could you point me to the code which does that please? Thanks.
